### ISSUE TITLE
panic: Failed to get k8s cluster router

### ISSUE THREAD

**Issue by phoracek** [phoracek/ovn-kubernetes-kubevirtci#2]
While testing on kubevirtci I hit this panic. I created two pods requesting secondary ovn networks, pod on compute node was created successfully. Pod on master node failed to be created.

This panic appears right after OVN plugin is deployed.

ovnkube-master logs (panic: Failed to get k8s cluster router):

```
================== ovnkube.sh ================
==================== hostname: node01 
==================== compatible with version 1 daemonsets
Image built from ovn-kubernetes ref: master  commit: e565e75808cd18cce11df8a1943842df99432b6b
OVN_NORTH tcp://192.168.66.101:6641 OVN_NORTHD_OPTS --db-nb-sock=/var/run/openvswitch/ovnnb_db.sock --db-sb-sock=/var/
run/openvswitch/ovnsb_db.sock                                                                                        
OVN_SOUTH tcp://192.168.66.101:6642
OVN_CONTROLLER_OPTS --ovn-controller-log=-vconsole:emer
OVN_NET_CIDR 10.128.0.0/14
OVN_SVC_CIDR 10.96.0.0/12
K8S_APISERVER https://192.168.66.101:6443
OVNKUBE_LOGLEVEL 4
=============== wait for ovs
info: Waiting for ovs to come up, waiting 10s ...
ovs came up in 1 10sec tries
=============== start ovn-northd ========== MASTER ONLY
OVN_NORTH=tcp://192.168.66.101:6641 OVN_SOUTH==tcp://192.168.66.101:6642 ovn_northd_opts=--db-nb-sock=/var/run/openvsw
itch/ovnnb_db.sock --db-sb-sock=/var/run/openvswitch/ovnsb_db.sock                                                   
Starting ovn-northd.
=============== start ovn-master (wait for northbd) ========== MASTER ONLY
=============== start ovn-master ========== MASTER ONLY
=============== start ovn-controller (wait for northdb)
=============== start ovn-controller
Starting ovn-controller.
=============== start ovn-node
=============== done starting daemons =================
panic: Failed to get k8s cluster router

goroutine 1 [running]:
main.runOvnKube(0xc4202f11e0, 0x0, 0x0)
        /go-controller/_output/go/src/github.com/openvswitch/ovn-kubernetes/go-controller/cmd/ovnkube/ovnkube.go:259 +
0x1c6b                                                                                                               
main.main.func1(0xc4202f11e0, 0xc4202f11e0, 0xc4203d57ff)
        /go-controller/_output/go/src/github.com/openvswitch/ovn-kubernetes/go-controller/cmd/ovnkube/ovnkube.go:117 +
0x2b                                                                                                                 
github.com/openvswitch/ovn-kubernetes/go-controller/vendor/github.com/urfave/cli.HandleAction(0x1165a20, 0x1395e20, 0x
c4202f11e0, 0xc42009f980, 0x0)                                                                                       
        /go-controller/_output/go/src/github.com/openvswitch/ovn-kubernetes/go-controller/vendor/github.com/urfave/cli
/app.go:501 +0xd2                                                                                                    
github.com/openvswitch/ovn-kubernetes/go-controller/vendor/github.com/urfave/cli.(*App).Run(0xc420450e00, 0xc420010140
, 0x13, 0x14, 0x0, 0x0)                                                                                              
        /go-controller/_output/go/src/github.com/openvswitch/ovn-kubernetes/go-controller/vendor/github.com/urfave/cli
/app.go:268 +0x653                                                                                                   
main.main()
        /go-controller/_output/go/src/github.com/openvswitch/ovn-kubernetes/go-controller/cmd/ovnkube/ovnkube.go:120 +
0xabe                                                                                                                
node01
Wed Oct 24 14:10:35 UTC 2018
==================== ovnkube-master =================== 
====================== ovnnb_db.pid
4228
 
====================== ovnsb_db.pid
4236
 
====================== ovs-vswitchd.pid
4036
 
====================== ovsdb-server.pid
3994
 
====================== ovsdb-server-nb.log
2018-10-24T14:10:29.842Z|00001|vlog|INFO|opened log file /var/log/openvswitch/ovsdb-server-nb.log
2018-10-24T14:10:29.855Z|00002|ovsdb_server|INFO|ovsdb-server (Open vSwitch) 2.9.0
 
====================== ovsdb-server-sb.log 
2018-10-24T14:10:29.880Z|00001|vlog|INFO|opened log file /var/log/openvswitch/ovsdb-server-sb.log
2018-10-24T14:10:29.884Z|00002|ovsdb_server|INFO|ovsdb-server (Open vSwitch) 2.9.0
 
====================== ovn-northd.pid
4242
 
====================== ovn-northd.log
2018-10-24T14:10:29.906Z|00001|vlog|INFO|opened log file /var/log/openvswitch/ovn-northd.log
2018-10-24T14:10:29.907Z|00002|reconnect|INFO|unix:/var/run/openvswitch/ovnnb_db.sock: connecting...
2018-10-24T14:10:29.907Z|00003|reconnect|INFO|unix:/var/run/openvswitch/ovnsb_db.sock: connecting...
2018-10-24T14:10:29.907Z|00004|reconnect|INFO|unix:/var/run/openvswitch/ovnnb_db.sock: connected
2018-10-24T14:10:29.907Z|00005|reconnect|INFO|unix:/var/run/openvswitch/ovnsb_db.sock: connected
2018-10-24T14:10:29.908Z|00006|ovn_northd|INFO|ovn-northd lock acquired. This ovn-northd instance is now active.
 
====================== ovnkube-master.pid
4248 
====================== ovnkube-master.log
time="2018-10-24T14:10:30Z" level=info msg="Setting annotations ovn_host_subnet=10.128.0.0/24 on node node01"
time="2018-10-24T14:10:30Z" level=info msg="Created HostSubnet 10.128.0.0/24"
time="2018-10-24T14:10:30Z" level=info msg="Setting annotations ovn_host_subnet=10.128.1.0/24 on node node02"
time="2018-10-24T14:10:30Z" level=info msg="Created HostSubnet 10.128.1.0/24"
time="2018-10-24T14:10:32Z" level=info msg="Setting annotations ovn= on pod ovnkube-master-c59b4"
time="2018-10-24T14:10:32Z" level=info msg="Setting annotations ovn= on pod kube-proxy-wgvvg"
time="2018-10-24T14:10:32Z" level=info msg="Setting annotations ovn= on pod netplugin-setup-4hl5h"
time="2018-10-24T14:10:32Z" level=error msg="failed to get the logical_switch node01 subnet, stderr: \"ovn-nbctl: no r
ow \\\"node01\\\" in table Logical_Switch\\n\" (exit status 1)"                                                      
time="2018-10-24T14:10:32Z" level=error msg="Error while creating logical port default_local-volume-provisioner-6lwpq 
stdout: \"\", stderr: \"ovn-nbctl: node01: switch name not found\\n\" (exit status 1)"                               
time="2018-10-24T14:10:32Z" level=info msg="Setting annotations ovn= on pod local-volume-provisioner-6lwpq"
time="2018-10-24T14:10:32Z" level=info msg="Setting annotations ovn= on pod kube-proxy-h4s5k"
time="2018-10-24T14:10:32Z" level=error msg="Error while creating logical port kube-system_coredns-78fcdf6894-m2pkl st
dout: \"\", stderr: \"ovn-nbctl: node01: switch name not found\\n\" (exit status 1)"                                 
time="2018-10-24T14:10:32Z" level=info msg="Setting annotations ovn= on pod coredns-78fcdf6894-m2pkl"
time="2018-10-24T14:10:32Z" level=info msg="Setting annotations ovn= on pod kube-multus-ds-amd64-t8pm7"
time="2018-10-24T14:10:32Z" level=error msg="Error while creating logical port kube-system_coredns-78fcdf6894-9vsz5 st
dout: \"\", stderr: \"ovn-nbctl: node01: switch name not found\\n\" (exit status 1)"                                 
time="2018-10-24T14:10:32Z" level=info msg="Setting annotations ovn= on pod coredns-78fcdf6894-9vsz5"
time="2018-10-24T14:10:32Z" level=error msg="failed to get the logical_switch node02 subnet, stderr: \"ovn-nbctl: no r
ow \\\"node02\\\" in table Logical_Switch\\n\" (exit status 1)"                                                      
time="2018-10-24T14:10:32Z" level=error msg="Error while creating logical port default_local-volume-provisioner-hr6d7 
stdout: \"\", stderr: \"ovn-nbctl: node02: switch name not found\\n\" (exit status 1)"                               
time="2018-10-24T14:10:32Z" level=info msg="Setting annotations ovn= on pod local-volume-provisioner-hr6d7"
time="2018-10-24T14:10:32Z" level=info msg="Setting annotations ovn= on pod kube-apiserver-node01"
time="2018-10-24T14:10:32Z" level=info msg="Setting annotations ovn= on pod kube-controller-manager-node01"
time="2018-10-24T14:10:32Z" level=info msg="Setting annotations ovn= on pod kube-scheduler-node01"
time="2018-10-24T14:10:32Z" level=info msg="Setting annotations ovn= on pod ovs-ovn-sbvdr"
time="2018-10-24T14:10:32Z" level=info msg="Setting annotations ovn= on pod netplugin-setup-9qstv"
time="2018-10-24T14:10:33Z" level=info msg="Setting annotations ovn= on pod kube-multus-ds-amd64-nxvqc"
time="2018-10-24T14:10:33Z" level=info msg="Setting annotations ovn= on pod kube-flannel-ds-amd64-s6khp"
time="2018-10-24T14:10:33Z" level=info msg="Setting annotations ovn= on pod ovnkube-mw2cm"
time="2018-10-24T14:10:33Z" level=info msg="Setting annotations ovn= on pod kube-flannel-ds-amd64-rsvbz"
time="2018-10-24T14:10:34Z" level=info msg="Setting annotations ovn= on pod etcd-node01"
time="2018-10-24T14:10:34Z" level=info msg="Setting annotations ovn= on pod ovs-ovn-7mfnl"
 
==================== ovnkube =================== 
====================== ovn-controller.pid
4278
 
====================== ovn-controller.log
2018-10-24T14:10:29.957Z|00001|vlog|INFO|opened log file /var/log/openvswitch/ovn-controller.log
2018-10-24T14:10:29.959Z|00002|reconnect|INFO|unix:/var/run/openvswitch/db.sock: connecting...
2018-10-24T14:10:29.959Z|00003|reconnect|INFO|unix:/var/run/openvswitch/db.sock: connected
2018-10-24T14:10:29.965Z|00004|main|INFO|OVN OVSDB remote not specified.  Waiting...
2018-10-24T14:10:30.839Z|00005|main|INFO|OVN OVSDB remote not specified.  Waiting...
2018-10-24T14:10:30.847Z|00006|reconnect|INFO|tcp:192.168.66.101:6642: connecting...
2018-10-24T14:10:30.847Z|00007|reconnect|INFO|tcp:192.168.66.101:6642: connected
2018-10-24T14:10:30.849Z|00008|chassis|INFO|Need to specify an encap type and ip
2018-10-24T14:10:30.850Z|00009|chassis|INFO|Need to specify an encap type and ip
2018-10-24T14:10:30.850Z|00010|chassis|INFO|Need to specify an encap type and ip
2018-10-24T14:10:30.856Z|00011|ofctrl|INFO|unix:/var/run/openvswitch/br-int.mgmt: connecting to switch
2018-10-24T14:10:30.856Z|00012|rconn|INFO|unix:/var/run/openvswitch/br-int.mgmt: connecting...
2018-10-24T14:10:30.856Z|00013|rconn|WARN|unix:/var/run/openvswitch/br-int.mgmt: connection failed (No such file or di
rectory)                                                                                                             
2018-10-24T14:10:30.856Z|00014|rconn|INFO|unix:/var/run/openvswitch/br-int.mgmt: waiting 1 seconds before reconnect
2018-10-24T14:10:30.856Z|00015|pinctrl|INFO|unix:/var/run/openvswitch/br-int.mgmt: connecting to switch
2018-10-24T14:10:30.856Z|00016|rconn|INFO|unix:/var/run/openvswitch/br-int.mgmt: connecting...
2018-10-24T14:10:30.856Z|00017|rconn|WARN|unix:/var/run/openvswitch/br-int.mgmt: connection failed (No such file or di
rectory)                                                                                                             
2018-10-24T14:10:30.856Z|00018|rconn|INFO|unix:/var/run/openvswitch/br-int.mgmt: waiting 1 seconds before reconnect
2018-10-24T14:10:31.508Z|00019|rconn|INFO|unix:/var/run/openvswitch/br-int.mgmt: connecting...
2018-10-24T14:10:31.508Z|00020|rconn|WARN|unix:/var/run/openvswitch/br-int.mgmt: connection failed (No such file or di
rectory)                                                                                                             
2018-10-24T14:10:31.508Z|00021|rconn|INFO|unix:/var/run/openvswitch/br-int.mgmt: waiting 2 seconds before reconnect
2018-10-24T14:10:31.508Z|00022|rconn|INFO|unix:/var/run/openvswitch/br-int.mgmt: connecting...
2018-10-24T14:10:31.508Z|00023|rconn|WARN|unix:/var/run/openvswitch/br-int.mgmt: connection failed (No such file or di
rectory)                                                                                                             
2018-10-24T14:10:31.508Z|00024|rconn|INFO|unix:/var/run/openvswitch/br-int.mgmt: waiting 2 seconds before reconnect
2018-10-24T14:10:33.504Z|00025|rconn|INFO|unix:/var/run/openvswitch/br-int.mgmt: connecting...
2018-10-24T14:10:33.504Z|00026|rconn|INFO|unix:/var/run/openvswitch/br-int.mgmt: connecting...
2018-10-24T14:10:33.504Z|00027|rconn|INFO|unix:/var/run/openvswitch/br-int.mgmt: connected
2018-10-24T14:10:33.504Z|00028|rconn|INFO|unix:/var/run/openvswitch/br-int.mgmt: connected
 
====================== ovnkube.pid
 
====================== ovnkube.log
time="2018-10-24T14:10:30Z" level=error msg="Error starting node node01, no annotation found on node for subnet - <nil
>"                                                                                                                   
time="2018-10-24T14:10:31Z" level=info msg="Node node01 ready for ovn initialization with subnet 10.128.0.0/24"
time="2018-10-24T14:10:31Z" level=error msg="Failed to get k8s cluster router"
 
====================== ovn-k8s-cni-overlay.log
```

Pod startup logs:

```
  Normal   Scheduled               7m                 default-scheduler  Successfully assigned default/on-green9 to no
de01                                                                                                                 
  Warning  FailedCreatePodSandBox  7m                 kubelet, node01    Failed create pod sandbox: rpc error: code = 
Unknown desc = failed to set up sandbox container "bdbca18bf790af129aa02db01bf9f4576b9ae18c263bcb512e10561eacad1250" n
etwork for pod "on-green9": NetworkPlugin cni failed to set up pod "on-green9_default" network: Multus: Err in tearing
 down failed plugins: Multus: error in invoke Delegate add - "ovn-k8s-cni-overlay": failed to send CNI request: Post h
ttp://dummy/: dial unix /var/run/ovn-kubernetes/cni//ovn-cni-server.sock: connect: no such file or directory         
  Warning  FailedCreatePodSandBox  7m                 kubelet, node01    Failed create pod sandbox: rpc error: code = 
Unknown desc = failed to set up sandbox container "cd41951c907996233adbec42f744496d33e831cca367266f6bbfbb8eaccadd48" n
etwork for pod "on-green9": NetworkPlugin cni failed to set up pod "on-green9_default" network: Multus: Err in tearing
 down failed plugins: Multus: error in invoke Delegate add - "ovn-k8s-cni-overlay": failed to send CNI request: Post h
ttp://dummy/: dial unix /var/run/ovn-kubernetes/cni//ovn-cni-server.sock: connect: no such file or directory         
  Warning  FailedCreatePodSandBox  7m                 kubelet, node01    Failed create pod sandbox: rpc error: code = 
Unknown desc = failed to set up sandbox container "c58fd3d2ffb3593c778a4286766aec677e911acb07463d2eb6a8460940c7af60" n
etwork for pod "on-green9": NetworkPlugin cni failed to set up pod "on-green9_default" network: Multus: Err in tearing
 down failed plugins: Multus: error in invoke Delegate add - "ovn-k8s-cni-overlay": failed to send CNI request: Post h
ttp://dummy/: dial unix /var/run/ovn-kubernetes/cni//ovn-cni-server.sock: connect: no such file or directory         
  Warning  FailedCreatePodSandBox  7m                 kubelet, node01    Failed create pod sandbox: rpc error: code = 
Unknown desc = failed to set up sandbox container "17bfb07d8fe8ca83fb1fd3d3bf9c2724eef37076602b20ffe474de7133ef25e5" n
etwork for pod "on-green9": NetworkPlugin cni failed to set up pod "on-green9_default" network: Multus: Err in tearing
 down failed plugins: Multus: error in invoke Delegate add - "ovn-k8s-cni-overlay": failed to send CNI request: Post h
ttp://dummy/: dial unix /var/run/ovn-kubernetes/cni//ovn-cni-server.sock: connect: no such file or directory         
  Warning  FailedCreatePodSandBox  7m                 kubelet, node01    Failed create pod sandbox: rpc error: code = 
Unknown desc = failed to set up sandbox container "40e0ba36fb86f94420e5bbd83af49614f889381c92d1ad632eabc3fc4e7fa26d" n
etwork for pod "on-green9": NetworkPlugin cni failed to set up pod "on-green9_default" network: Multus: Err in tearing
 down failed plugins: Multus: error in invoke Delegate add - "ovn-k8s-cni-overlay": failed to send CNI request: Post h
ttp://dummy/: dial unix /var/run/ovn-kubernetes/cni//ovn-cni-server.sock: connect: no such file or directory         
  Warning  FailedCreatePodSandBox  7m                 kubelet, node01    Failed create pod sandbox: rpc error: code = 
Unknown desc = failed to set up sandbox container "6ec95d98e6db522cd25b8c30847afc6af000e5f11fa78510c7b6cd9887259735" n
etwork for pod "on-green9": NetworkPlugin cni failed to set up pod "on-green9_default" network: Multus: Err in tearing
 down failed plugins: Multus: error in invoke Delegate add - "ovn-k8s-cni-overlay": failed to send CNI request: Post h
ttp://dummy/: dial unix /var/run/ovn-kubernetes/cni//ovn-cni-server.sock: connect: no such file or directory         
  Warning  FailedCreatePodSandBox  7m                 kubelet, node01    Failed create pod sandbox: rpc error: code = 
Unknown desc = failed to set up sandbox container "7c1718789a94015f4897f04a1758214166a0040b5835910ae598b93900528567" n
etwork for pod "on-green9": NetworkPlugin cni failed to set up pod "on-green9_default" network: Multus: Err in tearing
 down failed plugins: Multus: error in invoke Delegate add - "ovn-k8s-cni-overlay": failed to send CNI request: Post h
ttp://dummy/: dial unix /var/run/ovn-kubernetes/cni//ovn-cni-server.sock: connect: no such file or directory         
  Warning  FailedCreatePodSandBox  7m                 kubelet, node01    Failed create pod sandbox: rpc error: code = 
Unknown desc = failed to set up sandbox container "1630e9fc4c60ed2a13e23c51e1da4b313df5897c02f9e36a1e852a644bb6d81e" n
etwork for pod "on-green9": NetworkPlugin cni failed to set up pod "on-green9_default" network: Multus: Err in tearing
 down failed plugins: Multus: error in invoke Delegate add - "ovn-k8s-cni-overlay": failed to send CNI request: Post h
ttp://dummy/: dial unix /var/run/ovn-kubernetes/cni//ovn-cni-server.sock: connect: no such file or directory         
  Warning  FailedCreatePodSandBox  7m                 kubelet, node01    Failed create pod sandbox: rpc error: code = 
Unknown desc = failed to set up sandbox container "f4f4072254f0f3256dd895430827f7271538b66fc2740f3dd6cc5d11d035d424" n
etwork for pod "on-green9": NetworkPlugin cni failed to set up pod "on-green9_default" network: Multus: Err in tearing
 down failed plugins: Multus: error in invoke Delegate add - "ovn-k8s-cni-overlay": failed to send CNI request: Post h
ttp://dummy/: dial unix /var/run/ovn-kubernetes/cni//ovn-cni-server.sock: connect: no such file or directory         
  Normal   SandboxChanged          7m (x12 over 7m)   kubelet, node01    Pod sandbox changed, it will be killed and re
-created.                                                                                                            
  Warning  FailedCreatePodSandBox  2m (x253 over 7m)  kubelet, node01    (combined from similar events): Failed create
 pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "c5987781b187955027bfaadef6f95f0498d
34e41a33e3b1715f11b17e318c525" network for pod "on-green9": NetworkPlugin cni failed to set up pod "on-green9_default"
 network: Multus: Err in tearing down failed plugins: Multus: error in invoke Delegate add - "ovn-k8s-cni-overlay": fa
iled to send CNI request: Post http://dummy/: dial unix /var/run/ovn-kubernetes/cni//ovn-cni-server.sock: connect: no 
such file or directory                                                                                               

```

**Comment by phoracek** [comment]
Looks like it's a firewall issue.

**Edit** it's not

**Comment by yuvalif** [comment]
same issue is constantly happening with 2 nodes as well

**Comment by phoracek** [comment]
Yes. But sometimes it passes ok. It is for sure raceful. I tried to `make cluster-up` and then `make cluster-sync-ovn` twice in a row and it worked in most of the times.

Also, it looks like sometimes after the first `make cluster-sync-ovn` it creates no elements on the northbound database, sometimes it creates just part of them (node01 is ok, node02 is not, etc).

I think we need to fix ovn-kubernetes code so it retries some of the init operations in case it fails.

**Comment by yuvalif** [comment]
maybe instead of the deamon-set based deployment, do an explicit one?
you can look into this repo: https://github.com/yuvalif/onv-k8s-local-lab
with some installation scripts

**Comment by phoracek** [comment]
I mean, we could try, but we eventually want to go with daemonset based one, so we have to debug it sooner or later. Also, it would make deployment harder, right now, daemon sets get their rights to access cluster and info about OVN configuration from Kubernetes.

How would using explicit deployment help us?

**Comment by yuvalif** [comment]
explicit deployment is how we do that on kubevirt ci using a provision.sh script -  you have full control on what is done when.

**Comment by phoracek** [comment]
If I wont be able to stabilize the DS deployment this week, I will change it for explicit one. But I think we should resolve it ASAP.
